language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build -f netcoreapp2.0
 - dotnet test ./AdvancedHttpClient.IntegrationTests/AdvancedHttpClient.IntegrationTests.csproj -v n -f netcoreapp2.0
 - dotnet test ./AdvancedHttpClient.UnitTests/AdvancedHttpClient.UnitTests.csproj -v n -f netcoreapp2.0
